.\" This is the pyMoioSMS man page.
.\"
.\" Copyright (c) 2010, Carlo Stemberger.
.\" Released by the author into the public domain.
.\"
.\" TODO: use help2man?
.\"
.TH PYMOIOSMS 1 "April 2010" "pyMoioSMS 0.0" "User Commands"
.SH NAME
pyMoioSMS \- send SMS via Web services
.
.SH SYNOPSIS
.\"
.\" TODO: syntax to decide
.\"
.B pymoiosms
.br
.B pymoiosms
.RB [ -s | -h | -v ]
.br
.B pymoiosms
.RB [ -a
.IR "name phone_number" ]
.br
.B pymoiosms
.RI [ "phone_number text" " [" sender "] [" "\fB-p\fP proxy" ]]
.
.SH DESCRIPTION
.B pyMoioSMS
is ... bla bla bla... TODO
.
.SH OPTIONS
.IP "\fB-a\fP \fIname phone_number\fP, \fB--add\fP \fIname phone_number\fP"
add a phone number into the phone book and exit
.IP "\fB-p\fP \fIproxy\fP, \fB--proxy\fP \fIproxy\fP"
TODO
.IP "\fB-s\fP, \fB--show\fP"
display the phone book and exit
.IP "\fB-h\fP, \fB--help\fP"
display this help and exit
.IP "\fB-v\fP, \fB--version\fP"
print version information on standard output and exit
.\"TODO
.
.SH EXAMPLES
TODO
.\"
.SH FILES
TODO
.
.SH AUTHOR
Written by Silvio Moioli, Donatello Volonghi and Thomas Bertani.
.
.SH REPORTING BUGS
http://github.com/sylarpowa/pyMoioSMS/issues
.
.SH SEE ALSO
TODO
