.\" This is the pyMoioSMS man page.
.\"
.\" Copyright (c) 2010, Carlo Stemberger.
.\" Released by the author into the public domain.
.\"
.TH PYMOIOSMS 1 "April 2010" "pyMoioSMS 0.0" "User Commands"
.\"
.SH NAME
pyMoioSMS \- send SMS via Web services
.\"
.SH SYNOPSIS
.\"
.\" TODO: syntax to decide
.\"
.B pymoiosms
.br
.B pymoiosms
.RB [ -s | -h | -V ]
.br
.B pymoiosms
.RB [ -a
.IR "name number" ]
.br
.RB TODO
.\"
.SH DESCRIPTION
.B pyMoioSMS
is ... bla bla bla... TODO
.\"
.SH OPTIONS
.IP "-a, --add"
add a phone number into the phone book and exit
.IP "-s, --show"
display the phone book and exit
.IP "-h, --help"
display this help and exit
.IP "-V, --version"
print version information on standard output and exit
.\"TODO
.\"
.SH EXAMPLES
TODO
.\"
.SH FILES
TODO
.\"
.SH AUTHOR
Written by Silvio Moioli, Donatello Volonghi and Thomas Bertani.
.\"
.SH REPORTING BUGS
http://github.com/sylarpowa/pyMoioSMS/issues
.\"
.SH SEE ALSO
TODO
